import turtle
turtle.hideturtle()

turtle.color("purple")
turtle.begin_fill()
turtle.fd(100)
turtle.left(72)
turtle.fd(100)
turtle.left(72)
turtle.fd(100)
turtle.left(72)
turtle.fd(100)
turtle.left(72)
turtle.fd(100)
turtle.left(72)
turtle.end_fill()

turtle.penup()
turtle.goto(-200,200)
turtle.pendown()

turtle.color("red")
turtle.begin_fill()
turtle.circle(50)
turtle.end_fill()

turtle.penup()
turtle.goto(-250, -250)
turtle.pendown()

turtle.color("blue")
turtle.begin_fill()
turtle.fd(50)
turtle.left(120)
turtle.fd(50)
turtle.left(120)
turtle.fd(50)
turtle.left(120)
turtle.end_fill()

turtle.penup()
turtle.goto(200, -150)
turtle.pendown()

turtle.color("black")
turtle.begin_fill()
turtle.fd(50)
turtle.right(90)
turtle.fd(50)
turtle.right(90)
turtle.fd(50)
turtle.right(90)
turtle.fd(50)
turtle.right(90)
turtle.end_fill()

turtle.exitonclick()